# Site/SEO settings
email:
permalink: /:year/:month/:day/:title/
google_analytics:

title: "Cyber Brick Project"
description: "by mwilczek.net"
url: "https://cyber-brick-project.github.io/"
baseurl: ""
twitter_username:
default_img: "https://cyber-brick-project.github.io/assets/images/austin-smart-vPe0ltATD2k-unsplash.jpg"

# Profile settings
name: "Cyber Brick Project"
profile_img: "https://cyber-brick-project.github.io/assets/logo.git/logo-square.png"
profile: "Project born from passion for Lego and computer science, and engineering. Focused mainly on automating Lego, but also on preparing proper documentations, covering both business cases and technical details."
social:
  github: https://github.com/cyber-brick-project
  user-circle: https://mwilczek-net.github.io/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-autoprefixer
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - _screenshots
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

include: ["_pages"]

# Pagination
paginate: 10
paginate_path: "/blog/page-:num"

# Sass
sass:
  style: compressed
